### ISSUE TITLE
Cannot find module key tar

### ISSUE THREAD

**Issue by chasingtheflow** [ServiceNow/servicenow-cli#2]
Hey, 

When trying to create a project I get the following:

 ~/D/R/now-cli> snc ui-component project --name Example
node:internal/modules/cjs/loader:942
  throw err;
  ^

Error: Cannot find module 'keytar'
Require stack:
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/keytar-synthesizer.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/index.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/index.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/index.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/index.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/common/connection-utils.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/api/index.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/runner/plugin-factory.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/runner/index.js
- /Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at rebuildKeytarBindings (/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/keytar-synthesizer.js:23:391)
    at module.exports (/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/keytar-synthesizer.js:23:610)
    at Object.<anonymous> (/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/index.js:23:202)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/keytar-synthesizer.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/credential-manager/index.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/auth/index.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/connection/index.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli-glide/index.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/common/connection-utils.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/api/index.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/runner/plugin-factory.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/runner/index.js',
    '/Users/billy/.snc/.extensions/ui-component/node_modules/@servicenow/cli/src/index.js'
  ]
}

Node.js v18.0.0

**Comment by chiarnglin** [comment]
Please submit a support request through https://support.servicenow.com/ on this one. Thanks.
